<?php
$title = "Add new cms";
$this->headTitle($title);
?>

<h1 id="title"><?php echo $this->escapeHtml($title); ?></h1>

<div id="dashboard">
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('cms/add', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);

?>

<!--<div class="ui-fieldset">
	<div class="ui-formRow">
		<div class="ui-formCol1"><?php echo $this->formLabel($form->get('fk_cms_folder_type')); ?></div>
		<div class="ui-formCol2"><?php echo $this->formSelect($form->get('fk_cms_folder_type')); ?></div>
	</div>

	<?php echo $this->formHidden($form->get('id_cms_folder')); ?>

	<div class="ui-formRow">
		<div class="ui-formCol1"><?php echo $this->formLabel($form->get('key')); ?></div>
		<div class="ui-formCol2"><?php echo $this->formText($form->get('key')); ?></div>
	</div>
	<div class="ui-formRow">
		<div class="ui-formCol1"><?php echo $this->formLabel($form->get('description')); ?></div>
		<div class="ui-formCol2"><?php echo $this->formText($form->get('description')); ?></div>
	</div>
	<div class="ui-formRow">
		<div class="ui-formCol1"><?php echo $this->formCheckbox($form->get('is_active')); ?></div>
		<div class="ui-formCol2"><?php echo $this->formLabel($form->get('is_active')); ?></div>
	</div>
	<div class="ui-formRow">
		<div class="ui-formCol1"><?php echo $this->formCheckbox($form->get('is_published')); ?></div>
		<div class="ui-formCol2"><?php echo $this->formLabel($form->get('is_published')); ?></div>
	</div>

	<div class="ui-formRow ui-submit-field">
		<div class="ui-formCol1"></div>
		<div class="ui-formCol2"><?php echo $this->formSubmit($form->get('submit')); ?></div>
	</div>
</div>-->

<?php echo $this->form()->closeTag();
?>
</div>