<?php
$title = "Add new cms";
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('cms/add', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id_cms_folder'));
echo $this->formRow($form->get('cms_folder'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>