<?php
$title = "CMS Modification";
$this->headTitle($title);
?>

<h1 id="title"><?php echo $this->escapeHtml($title); ?></h1>

<div id="dashboard">
<?php
echo $this->partial('cms/detail');
echo $this->partial('cms/item');
?>


<?php //$this->partial('form.phtml', array('form' => $this->itemForm));
//$form = $this->itemForm;
//$itemForm->setAttribute('action', $this->url('cms/edit', array('action' => 'edit')));
//$itemForm->prepare();

//echo $this->form()->openTag($form);
//echo $this->formCollection($form);
//echo $this->form()->closeTag();
?>
</div>