<header>
	<div>
		<ul class="first-navigation">
			<li><a href="<?php echo $this->url('home') ?>">Catalog</a>
				<ul class="second-navigation">
					<li><a href="/">PET</a></li>
					<li><a href="/">Categories</a></li>
				</ul>
			</li>
			<li><a href="<?php echo $this->url('home') ?>">Content</a>
				<ul class="second-navigation">
					<li><a href="/">CMS</a></li>
				</ul>
			</li>
			<li><a href="<?php echo $this->url('home') ?>">System</a>
				<ul class="second-navigation">
					<li><a href="/">Configuration</a></li>
				</ul>
			</li>
			<li><a href="<?php echo $this->url('home') ?>">Logout</a></li>
		</ul>
	</div>
</header>