<?php
    require_once(dirname(__FILE__) . '/dictionary.php');
    $dictionary = 'Dictionary';
    $this->headMeta()->appendName('description', 'In hóa đơn VAT, cardvist và bao thư với chất lượng và giá cả tốt')
            ->appendName('keywords', 'hóa đơn VAT, hóa đơn GTGT')
            ->appendName('robots', 'index, nofollow');
?>
<div class="home-floor-layout-container">
<div class="left-sidebar">
    <ul>
    <?php foreach ($this->all_product_types as $ptype): ?>
        <li>
            <a class="category-tree" href="<?php echo $this->url('home',array(),array('force_canonical' => true)); ?>"><?php echo $this->escapeHtml($ptype->name); ?></a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>

<div class="homepage-banner">
    <div id="left-arrow"></div>
    <div class="banner-scroll">
    <img class="active" src="<?php echo $this->serverUrl() . $this->basePath('/img/homepage_banner_4.jpg'); ?>" title="homepage banner" alt="homepage banner" />
    <img src="<?php echo $this->serverUrl() . $this->basePath('/img/homepage_banner_3.jpg'); ?>" title="homepage banner" alt="homepage banner" />
    <img id="first-banner" src="<?php echo $this->serverUrl() . $this->basePath('/img/homepage_banner_5.jpg'); ?>" title="homepage banner" alt="homepage banner" />
    </div>
    <div id="right-arrow"></div>
</div>

<?php 
        $url = $this->url('home/block-template', array(
                                'controller' => 'cms',
                                'action' => 'staticBlock',
                                'key' => "ups",
                            ),
            array(
                'force_canonical' => true
                )); 
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER,1);
        $response = curl_exec($ch);
        curl_close($ch);
        echo($response);
    ?>
</div>

<div class="main-content">
    <?php foreach ($this->all_invoice_types as $invoice_type_entity): ?>
    <div class="floor">
        <div class="floor-separater"></div>
        <div class="floor-title">
            <?php echo $this->escapeHtml($invoice_type_entity->invoice_type_name); ?>
        </div>
        <div class="product-container">
        <div class="flex-left-navigator"></div>
        <div class="product-placeholder-content">
            <div class="product-list">
            <?php foreach ($this->products_by_invoice_type as $pite): ?>
                <?php if ($invoice_type_entity->invoice_type_id == $pite['invoice_type_fk']): ?>
                <div class="product-card">
                    <a class="product-card-img" href="<?php echo $this->url('home/product', array(
                            'controller' => 'index',
                            'action' => 'product',
                            'productname' => $dictionary::formatUrl(str_ireplace(' ', '-', strtolower($pite['general_name']))),
                            'id' => $pite['general_id']
                        ), array(
                            'force_canonical' => true
                        )); ?>"><img src="<?php echo $this->serverUrl() . $this->basePath($pite['source']); ?>" title="<?php echo $pite['title']; ?>" alt="<?php echo $pite['alt_tag']; ?>" /> </a>
                    <div class="product-name">
                        <span class="product-name-big" title="<?php echo $pite['general_name']; ?>"><?php echo $pite['general_name']; ?></span>
                    </div>
                    <div class="button-order">
                        <span class="button-order-text"><a id="detail-link" href="<?php echo $this->url('home/product', array(
                            'controller' => 'index',
                            'action' => 'product',
                            'productname' => $dictionary::formatUrl(str_ireplace(' ', '-', strtolower($pite['general_name']))),
                            'id' => $pite['general_id']
                        ), array(
                            'force_canonical' => true
                        )); ?>">Chi tiết</a></span>
                    </div>
                </div>
            <?php endif; ?>
            <?php endforeach; ?>
            </div>
        </div>
        <div class="flex-right-navigator"></div>
        </div>
    </div>
<?php endforeach; ?>
</div>