<?php
    $this->title = "Tin tức";
    $this->headTitle($this->title);
?>

<div class="news-list-container">
	<div class="news-title">Danh sách tin</div>
	<ul class="news-list">
		<li><a href="#">Tin tức 1</a></li>
		<li><a href="#">Tin tức 2</a></li>
		<li><a href="#">Tin tức 3</a></li>
		<li><a href="#">Tin tức 4</a></li>
		<li><a href="#">Tin tức 5</a></li>
		<li><a href="#">Tin tức 6</a></li>
		<li><a href="#">Tin tức 7</a></li>
		<li><a href="#">Tin tức 8</a></li>
		<li><a href="#">Tin tức 9</a></li>
		<li><a href="#">Tin tức 10</a></li>
		<li><a href="#">Tin tức 11</a></li>
		<li><a href="#">Tin tức 12</a></li>
	</ul>
	<div class="pager">
		<div class="prev-pager-navigator">Previous</div>
		<div class="paging">
			
		</div>
		<div class="next-pager-navigator">Next</div>
	</div>
</div>