<?php
    $this->title = "Tin tức";
    $this->headTitle($this->title);
?>

<?php 
        $url = $this->url('home/block-template', array(
                                'controller' => 'cms',
                                'action' => 'staticBlock',
                                'key' => "news-list",
                            ),
            array(
                'force_canonical' => true
                ));
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER,1);
        $response = curl_exec($ch);
        curl_close($ch);
       	echo($response);
?>