<?php
	$product = $this->currentProduct[0];
    $this->title = $product['general_name'];
    $this->headTitle($this->title);
    $images = $this->images;
?>

<div class="product-detail-page">
	<div class="header-breadcrumb">
	<ul>
	
		<li>
			<span class="header-breadcrumb-element">
				<?php echo $product['general_name']; ?>
			</span>
		</li>
	</ul>
	</div>
	

	<div class="product-info">
	<h1 id="product-title"><?php echo $product['general_name']; ?></h1>

	<div class="product-imagebox-layout" id="imagebox">
		<div id="product-gallery">
		<?php foreach ($images as $image): ?>
			<span class="gallery-image">
			<img src="<?php echo $this->serverUrl() . $this->basePath($image['source']); ?>" title="<?php echo $image['title']; ?>" alt="<?php echo $image['alt_tag']; ?>" width="44px" />
			</span>
		<?php endforeach; ?>
		</div>

		<span id="product-thumbnail" style="display:none">
			<img src="<?php echo $this->serverUrl() . $this->basePath($product['source']); ?>" title="<?php echo $product['title']; ?>" alt="<?php echo $product['alt_tag']; ?>"/>
		</span>
		<span id="product-image">
			<img src="<?php echo $this->serverUrl() . $this->basePath($product['source']); ?>" title="<?php echo $product['title']; ?>" alt="<?php echo $product['alt_tag']; ?>" width="350px" />
		</span>
	</div>

	<div class="product-description-wrapper">
		<span class="product-description-title">Thông tin sản phẩm <?php echo $product['general_name']; ?></span>
		<div class="product-description-content">
		<table>
			<tbody>
		<?php 
			$descriptionContent = trim($product['description_content'],".");
			$contentExploder = explode(".",$descriptionContent); 
			foreach ($contentExploder as $contentEntity):
				$contentSeparater = explode(":",trim($contentEntity)); ?>
				<tr>
					<?php foreach ($contentSeparater as $specificationColumn): ?>
						<td>
							<?php echo trim($specificationColumn); ?>
						</td>
					<?php endforeach; ?>
				</tr>
		<?php endforeach; ?>
			</tbody>
		</table>
		</div>
		
		<input id="order-button" type="submit" value="Đặt hàng" />
	</div>
	</div>
</div>