<?php
	require_once(dirname(__FILE__) . '/dictionary.php');
    $dictionary = 'Dictionary';

    if ('' == $this->invoiceName){
    	$this->headTitle($this->productName);
    	$this->headMeta()->appendName('description', $this->productName)
            ->appendName('keywords', $this->productName);
    } else {
    	$this->headTitle($this->invoiceName);
		$this->headMeta()->appendName('description', $this->invoiceName)
            ->appendName('keywords', $this->invoiceName);
    }
?>

<div class="product-detail-page">
	<div class="header-breadcrumb">
	<ul>
		<li>
			<span class="header-breadcrumb-element">
				<a href="<?php echo $this->url('home', array(), array(
                            'force_canonical' => true
                        )); ?>"><img src="<?php echo $this->serverUrl() . $this->basePath('/img/icon/1460242836_home_icon.png'); ?>" title="homepage banner" alt="homepage banner" /></a>
			</span>
		</li>
		<li>
			<span class="header-breadcrumb-element">
				<?php echo "/"; ?>
			</span>
		</li>
		<?php if ('' == $this->invoiceName): ?>
		<li>
			<span class="header-breadcrumb-element">
				<?php echo $this->productName; ?>
			</span>
		</li>
		<?php else: ?>
		<li>
			<span class="header-breadcrumb-element">
				<a href="<?php echo $this->url('home/product-url', array(
                            'controller' => 'index',
                            'action' => 'productUrl',
                            'producturl' => $this->productUrl
                        ), array(
                            'force_canonical' => true
                        )); ?>"><?php echo $this->productName; ?></a>
			</span>
		</li>
		<li>
			<span class="header-breadcrumb-element">
				<?php echo "/"; ?>
			</span>
		</li>
		<li>
			<span class="header-breadcrumb-element">
				<?php echo $this->invoiceName; ?>
			</span>
		</li>
		<?php endif; ?>
	</ul>
	</div>
	
	<div class="detail-list">
            <?php foreach ($this->productArray as $pite): ?>
                <div class="product-card">
                    <a class="product-card-img" href="<?php echo $this->url('home/product', array(
                            'controller' => 'index',
                            'action' => 'product',
                            'productname' => $dictionary::formatUrl(str_ireplace(' ', '-', strtolower($pite['general_name']))),
                            'id' => $pite['general_id']
                        ), array(
                            'force_canonical' => true
                        )); ?>"><img src="<?php echo $this->serverUrl() . $this->basePath($pite['source']); ?>" title="<?php echo $pite['title']; ?>" alt="<?php echo $pite['alt_tag']; ?>" /> </a>
                    <div class="product-name">
                        <span class="product-name-big" title="<?php echo $pite['general_name']; ?>"><?php echo $pite['general_name']; ?></span>
                    </div>
                    <div class="button-order">
                        <span class="button-order-text"><a id="detail-link" href="<?php echo $this->url('home/product', array(
                            'controller' => 'index',
                            'action' => 'product',
                            'productname' => $dictionary::formatUrl(str_ireplace(' ', '-', strtolower($pite['general_name']))),
                            'id' => $pite['general_id']
                        ), array(
                            'force_canonical' => true
                        )); ?>">Chi tiết</a></span>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
</div>