<h1 id="title">Administration PET</h1>

<div id="dashboard">
    <table>
        <tr>
        	<th>Category</th>
        	<th>SKU</th>
        	<th>Name</th>
        	<th>Image</th>
        </tr>
    <?php foreach ($this->all_invoice_types as $invoice_type_entity): ?>
        <div class="product-list">	
            <?php foreach ($this->products_by_invoice_type as $pite): ?>
                <?php if ($invoice_type_entity->invoice_type_id == $pite['invoice_type_fk']): ?>
                    <tr>
                    <td><?php echo $pite['invoice_type_name']; ?></td>
                    <td><?php echo $pite['sku']; ?></td>
                    <td><?php echo $pite['general_name']; ?></td>
                    <td><?php echo (strlen($pite['source']) > 0) ? $pite['source'] : ''; ?></td>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    <?php endforeach; ?>
	</table>
</div>