<?php
    $this->title = "Trang chủ";
    $this->headTitle($this->title);
?>

<div class="home-floor-layout-container">
<div class="left-sidebar">
    Left side
</div>

<div class="homepage-banner">
    Homepage banner
</div>

<div class="right-sidebar">
    Right side
</div>
</div>

<div class="main-content">
    <div class="first-floor">
        <div class="floor-title">
            Hóa đơn VAT
        </div>
    </div>
    Main content
</div>

<div>
    <?php echo var_dump($this->product_info); ?>
</div>


<table>
<tr>
<th>Name</th>
</tr>
    <?php foreach ($this->all_general_products as $entity): ?>
<tr>
    <td><?php echo $this->escapeHtml($entity->general_product_id); ?></td>
</tr>
<tr>
    <td><?php echo $this->escapeHtml($entity->sku); ?></td>
</tr>
    <?php endforeach;?>
</table>