<?php
    $this->title = "Trang chủ";
    $this->headTitle($this->title);
?>

<div class="home-floor-layout-container">
<div class="left-sidebar">
    Left side
</div>

<div class="homepage-banner">
    Homepage banner
</div>

<div class="right-sidebar">
    Right side
</div>
</div>

<div class="main-content">
    <?php foreach ($this->all_invoice_types as $invoice_type_entity): ?>
    <div class="floor">
        <div class="floor-separater"></div>
        <div class="floor-title">
            <?php echo $this->escapeHtml($invoice_type_entity->invoice_type_name); ?>
        </div>
        <div class="product-list">
            <?php foreach ($this->products_by_invoice_type as $pite): ?>
                <?php if ($invoice_type_entity->invoice_type_id == $pite['invoice_type_fk']): ?>
                <div class="product-card">
                    <a class="product-card-img" href="<?php echo $pite['source']; ?>"><img src="<?php echo $this->basePath('/img/kiendong_logo.png'); ?>" title="<?php echo $pite['title']; ?>" alt="<?php echo $pite['alt_tag']; ?>"/> </a>
                    <div class="product-name">
                        <span class="product-name-big" title="<?php echo $pite['general_name']; ?>"><?php echo $pite['general_name']; ?></span>
                    </div>
                    <div class="button-order">
                        <span class="button-order-text">Đặt hàng</span>
                    </div>
                </div>
            <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php endforeach; ?>
</div>