
<footer>
	<div class="footer-main">
	<?php 
		$url = $this->url('home/block-template', array(
	                            'controller' => 'cms',
	                            'action' => 'staticBlock',
	                            'key' => "footer-seo",
	                        ), array(
				'force_canonical' => true
				));
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, $url);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER,1);
		$response = curl_exec($ch);
		curl_close($ch);
		echo($response);
    ?>
    
    </div>
	<?php 
		$url = $this->url('home/block-template', array(
	                            'controller' => 'cms',
	                            'action' => 'staticBlock',
	                            'key' => "footer-info",
	                        ),
			array(
				'force_canonical' => true
				)); 
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, $url);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER,1);
		$response = curl_exec($ch);
		curl_close($ch);
		echo($response);
    ?>
</footer>