
<footer>
	<div class="footer-main">
	<?php 
		$url = $_SERVER['HTTP_HOST'] . $this->url('home/block-template', array(
	                            'controller' => 'cms',
	                            'action' => 'staticBlock',
	                            'key' => "footer-seo",
	                        )); 
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, $url);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER,1);
		$response = curl_exec($ch);
		curl_close($ch);
		echo($response);
    ?>

    <?php 
		$url = $_SERVER['HTTP_HOST'] . $this->url('home/block-template', array(
	                            'controller' => 'cms',
	                            'action' => 'staticBlock',
	                            'key' => "footer-social",
	                        ),
			array(
				'force_canonical' => true
				)); 
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, $url);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER,1);
		$response = curl_exec($ch);
		curl_close($ch);
		echo($response);
    ?>
    
    </div>
	<div class="footer-info">
		<p>
		CÔNG TY TNHH MỘT THÀNH VIÊN IN ẤN KIẾN ĐÔNG <br>
		Giấy CNĐKDN số: 0312163271. <br>
		Địa chỉ: 70D Đường HT18, Phường Hiệp Thành, Quận 12, TP. Hồ Chí Minh. <br>
		Số điện thoại: 08 6250 7100 - Fax: 08 6250 7101
		</p>
    </div>
</footer>