<?php
//    echo dirname(dirname(dirname(__DIR__))) . '\Alice\src\Alice\Controller\CmsController.php';
//    exit;
?>

<header>
	<div>
		<a class="header-logo" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/kiendong_logo.png') ?>" alt="kien dong in an"&nbsp;<?php echo $this->translate('in kien dong') ?> /></a>
		<p class="header-title"><i>inkiendong.com</i></p>

		<ul class="header-navigation">
			<li><a href="<?php echo $this->url('home'); ?>">Giới thiệu</a></li>
			<li><a href="<?php echo $this->url('home'); ?>">Sản phẩm</a></li>
			<li><a href="<?php echo $this->url('home/cms-template', array(
                            'controller' => 'cms',
                            'action' => 'index',
                            'key' => $this->requestHandler()->getFolderKeyById(12),
                        )); ?>"><?php echo $this->requestHandler()->customizeRequest($this->url('home/cms-template', array(
                            'controller' => 'cms',
                            'action' => 'index',
                            'key' => $this->requestHandler()->getFolderKeyById(12),
                        )), 12); ?>Bảng giá</a></li>
			<li><a href="<?php echo $this->url('home'); ?>">Tin tức</a></li>
			<li><a href="<?php echo $this->url('home'); ?>">Liên hệ</a></li>
		</ul>
	</div>
</header>