<?php
//    echo dirname(dirname(dirname(__DIR__))) . '\Alice\src\Alice\Controller\CmsController.php';
//    exit;
?>

<header>
	<div>
		<a class="header-logo" href="<?php echo $this->url('home', array(), array('force_canonical'=>true)); ?>"><img src="<?php echo $this->serverUrl() . $this->basePath('img/kiendong_logo.png') ?>" alt="kien dong in an"&nbsp;<?php echo $this->translate('in kien dong') ?> /></a>
		<p class="header-title"><i>inkiendong.com</i></p>

		<ul class="header-navigation">
			<li><a href="<?php echo $this->url('home', array(), array('force_canonical'=>true)); ?>">Giới thiệu</a></li>
			<li><a href="<?php echo $this->url('home', array(), array('force_canonical'=>true)); ?>">Sản phẩm</a></li>
			<li><a href="<?php echo $this->url('home/cms-template', array(
                            'controller' => 'cms',
                            'action' => 'index',
                            'key' => "bang-gia-hoa-don",
                        ), array(
                        	'force_canonical' => true
                        )); ?>">Bảng giá</a></li>
			<li><a href="<?php echo $this->url('home', array(), array('force_canonical'=>true)); ?>">Tin tức</a></li>
			<li><a href="<?php echo $this->url('home', array(), array('force_canonical'=>true)); ?>">Liên hệ</a></li>
		</ul>
	</div>
</header>