<header>
	<div>
		<a class="header-logo" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/kiendong_logo.png') ?>" alt="kien dong in an"&nbsp;<?php echo $this->translate('in kien dong') ?> /></a>
		<p class="header-title"><i>inkiendong.com</i></p>

		<ul class="header-navigation">
			<li><a href="<?php echo $this->url('home') ?>">Giới thiệu</a></li>
			<li><a href="<?php echo $this->url('home') ?>">Sản phẩm</a></li>
			<li><a href="<?php echo $this->url('home') ?>">Bảng giá</a></li>
			<li><a href="<?php echo $this->url('home') ?>">Tin tức</a></li>
			<li><a href="<?php echo $this->url('home') ?>">Liên hệ</a></li>
		</ul>
	</div>
</header>