 <div class="ups">
    <span class="ups-title"> Giới thiệu</span>
    <span>HOTLINE: <b>0907 164 787</b></span>
    <span>Giao hàng miễn phí trong nội thành Tp. HCM</span>
    <span>Chất liệu giấy Malaysia</span>
    <span>Mã vạch chống giả 2 chiều</span>
    <span>Dịch vụ khách hàng chu đáo</span>
    <span>Mẫu mã đa dạng, độc đáo</span>

    <span class="ups-title"> Đối tác</span>
    <span>Chính sách hấp dẫn cho đối tác bán hàng</span>
</div>