<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->headLink()
                        ->prependStylesheet($this->basePath('css/bob-style.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bob-main.js'))
            ->prependFile($this->basePath('js/main.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/modernizr-custom.js'))
            ->prependFile($this->basePath('js/lightbox.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/jquery-1.12.0.min.js'))
        ; ?>

    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
        </div>

        <?php echo $this->inlineScript() ?>
    </body>
</html>
